all:
	g++ -o a8 simul.cpp

1:
	./a8 tests/hazard1_reg.txt < tests/hazard1.txt 2> status8 > out8

2:
	./a8 tests/oneton_reg.txt < tests/oneton.txt 2> ./status8 > out8

3:
	./a8 tests/acc_reg.txt < tests/acc.txt 2> status8 > out8

4:
	./a8 tests/branch_f_reg.txt < tests/branch_f.txt 2> status8 > out8

5:
	./a8 tests/hazard2_reg.txt < tests/hazard2.txt 2> status8 > out8

6:
	./a8 tests/example_reg.txt < tests/example.txt 2> status8 > out8

7:
	./a8 tests/jump_reg.txt < tests/jump.txt 2> status8 > out8
