all:
	g++ -o a9 simul.cpp

1:
	./a9 tests/hazard1_reg.txt < tests/hazard1.txt 2> status9 > out9

2:
	./a9 tests/oneton_reg.txt < tests/oneton.txt 2> ./status9 > out9

3:
	./a9 tests/acc_reg.txt < tests/acc.txt 2> status9 > out9

4:
	./a9 tests/branch_f_reg.txt < tests/branch_f.txt 2> status9 > out9

5:
	./a9 tests/hazard2_reg.txt < tests/hazard2.txt 2> status9 > out9

6:
	./a9 tests/example_reg.txt < tests/example.txt 2> status9 > out9

7:
	./a9 tests/jump_reg.txt < tests/jump.txt 2> status9 > out9
