all:
	g++ -o a10 simul.cpp

1:
	./a10 tests/hazard1_reg.txt 0.5 2 < tests/hazard1.txt 2> status10 > out10

2:
	./a10 tests/oneton_reg.txt 0.5 2 < tests/oneton.txt 2> ./status10 > out10

3:
	./a10 tests/acc_reg.txt 0.5 2 < tests/acc.txt 2> status10 > out10

4:
	./a10 tests/branch_f_reg.txt 0.5 2 < tests/branch_f.txt 2> status10 > out10

5:
	./a10 tests/hazard2_reg.txt 0.5 2 < tests/hazard2.txt 2> status10 > out10

6:
	./a10 tests/example_reg.txt 0.5 2 < tests/example.txt 2> status10 > out10

7:
	./a10 tests/jump_reg.txt 0.5 2 < tests/jump.txt 2> status10 > out10
